# Generated by Django 3.2.7 on 2022-09-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=127, unique=True, verbose_name='device_id')),
                ('device_name', models.CharField(blank=True, max_length=32, verbose_name='设备名')),
                ('device_type', models.CharField(blank=True, max_length=32, verbose_name='设备类型')),
                ('online', models.BooleanField(default=False, verbose_name='在线状态')),
                ('config', models.TextField(default='{}', help_text='配置视频分辨率，帧率等', verbose_name='配置详情')),
                ('details', models.TextField(blank=True, verbose_name='代码详情')),
                ('updated_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '手机',
                'verbose_name_plural': '手机',
                'ordering': ('updated_time', 'created_time'),
            },
        ),
    ]
