# Generated by Django 3.2.7 on 2022-09-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='online',
        ),
    ]
