# Generated by Django 3.2.18 on 2023-05-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20230519_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='图片大小(KB)'),
        ),
    ]
