# Generated by Django 3.2.18 on 2023-05-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20230519_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ('-created_time',), 'verbose_name': '截图', 'verbose_name_plural': '截图'},
        ),
        migrations.RemoveField(
            model_name='picture',
            name='size',
        ),
        migrations.AlterField(
            model_name='picture',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
    ]
