# Generated by Django 4.2.4 on 2024-04-04 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0006_auto_20230519_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobile',
            options={'ordering': ('-updated_time',), 'verbose_name': '手机', 'verbose_name_plural': '手机'},
        ),
        migrations.AddField(
            model_name='mobile',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='config',
            field=models.TextField(default='{"recorder_enable": false, "recorder_format": "mp4", "audio": true, "video_codec": "h264", "audio_codec": "aac", "audio_source": "output", "max_size": 720, "video_bit_rate": 800000, "audio_bit_rate": 128000, "max_fps": 25, "tunnel_forward": true, "crop": "", "control": true, "show_touches": false, "stay_awake": true, "video_codec_options": "profile=1,level=2", "audio_codec_options": "", "video_encoder": "", "audio_encoder": "", "power_off_on_close": false, "clipboard_autosync": false, "power_on": true}', help_text='配置视频分辨率，帧率等', verbose_name='配置详情'),
        ),
        migrations.AlterField(
            model_name='video',
            name='config',
            field=models.TextField(default='{"recorder_enable": false, "recorder_format": "mp4", "audio": true, "video_codec": "h264", "audio_codec": "aac", "audio_source": "output", "max_size": 720, "video_bit_rate": 800000, "audio_bit_rate": 128000, "max_fps": 25, "tunnel_forward": true, "crop": "", "control": true, "show_touches": false, "stay_awake": true, "video_codec_options": "profile=1,level=2", "audio_codec_options": "", "video_encoder": "", "audio_encoder": "", "power_off_on_close": false, "clipboard_autosync": false, "power_on": true}', help_text='配置视频分辨率，帧率等', verbose_name='配置详情'),
        ),
    ]
